Update .git-templates/hooks/prepare-commit-msg Add install_packages.sh Update settings.json

diff --git a/dot_git-templates/hooks/executable_prepare-commit-msg b/dot_git-templates/hooks/executable_prepare-commit-msg
--- a/dot_git-templates/hooks/executable_prepare-commit-msg
+++ b/dot_git-templates/hooks/executable_prepare-commit-msg
@@ -30,15 +30,23 @@ declare -A prefix_emoji=(
 )
 
 commit_msg_file="$1"
-commit_msg_msg=$(cat "$commit_msg_file")
+
+if [[ ! -f "$commit_msg_file" ]]; then
+    echo "Error: Commit message file not found."
+    exit 1
+fi
+
+commit_msg_content=$(cat "$commit_msg_file")
+
+original_prefix=$(echo "$commit_msg_content" | awk '{print $1}')
+lowercase_prefix=$(echo "$commit_msg_content" | awk '{print tolower($1)}')
 
 prefix_found=false
-original_prefix=$(echo "$commit_msg_msg" | awk '{print $1}')
-lowercase_prefix=$(echo "$commit_msg_msg" | awk '{print tolower($1)}')
 
 for prefix in "${!prefix_emoji[@]}"; do
   if [[ "$lowercase_prefix" == "$prefix" ]]; then
     prefix_found=true
+    commit_msg_content=${commit_msg_content#"$original_prefix "}
     break
   fi
 done
@@ -47,11 +55,6 @@ if ! $prefix_found; then
   prefix="update"
 fi
 
-if [[ -z "$prefix_msg" ]]; then
-  prefix_msg=$prefix
-fi
-
-commit_desc=${commit_msg_msg#"$original_prefix" }
-new_commit_msg="${prefix_emoji[${prefix}]} $prefix_msg: $commit_desc"
+new_commit_msg="${prefix_emoji[${prefix}]} $prefix: $commit_msg_content"
 
 echo -e "$new_commit_msg" >"$commit_msg_file"
